/*
 * This source file was generated by the Gradle 'init' task
 */
package project.var;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void Transaction() {
        Transaction classUnderTest = new Transaction("12ANS",3000,true);
        assertEquals(classUnderTest.getTransactionId(),"12ANS");
        assertEquals(classUnderTest.getamount(),3000);
        assertEquals(classUnderTest. getcredit(),true);
    }
      @Test void Wallet() {
        Wallet classUnderTest = new Wallet("12ANS",10000);
        assertEquals(classUnderTest.getUpiId(),"12ANS");
        assertEquals(classUnderTest.getbalance(),10000);
    }

}
