/*
 * This source file was generated by the Gradle 'init' task
 */
package project.var;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDateTime;

class AppTest {
    @Test void Transaction() {
        Transaction classUnderTest = new Transaction("12ANS",3000,true,LocalDateTime.now());
        assertEquals(classUnderTest.getTransactionId(),"12ANS");
        assertEquals(classUnderTest.getamount(),3000);
        assertEquals(classUnderTest. getcredit(),true);
    }
      @Test void Wallet() {
        Wallet classUnderTest = new Wallet("12ANS",10000);
        assertEquals(classUnderTest.getUpiId(),"12ANS");
        assertEquals(classUnderTest.getbalance(),10000);
    }
     @Test void failedinitiation() {
       IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class,
            () -> new Wallet("12ANS",-1000));
        assertEquals("Balance cannot be negative", exception.getMessage());
    }

     @Test void negativewithdrawal() {
        Wallet classUnderTest = new Wallet("12ANS",10000);
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
            () -> classUnderTest.deductmoney(-200));
        assertEquals("Amount cannot be negative", exception.getMessage()); 
    }

     @Test void negativedeposit() {
        Wallet classUnderTest = new Wallet("12ANS",10000);
       IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
            () -> classUnderTest.addmoney(-200));
        assertEquals("Amount cannot be negative", exception.getMessage());
    }
   
    @Test void insufficientfunds() {
        Wallet classUnderTest = new Wallet("12ANS",10000);
       IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
            () -> classUnderTest.deductmoney(12200));
        assertEquals("balance is insufficient", exception.getMessage());
    }

    @Test void totalamountcredited(){
        Wallet  w = new Wallet("12ANS",10000);
        WalletAnalyser k = new WalletAnalyser(w);
        w.addmoney(2000);
        w.deductmoney(1000);
        w.addmoney(5000);
       assertEquals(k.totalamountcredited(), 7000);
    }
    @Test void totalamountdebited(){
        Wallet  w = new Wallet("12ANS",10000);
        WalletAnalyser k = new WalletAnalyser(w);
        w.addmoney(2000);
        w.deductmoney(1000);
        w.addmoney(5000);
       assertEquals(k.totalamountdebited(), 1000);
    }
   @Test void expenditure(){
         Wallet  w = new Wallet("12ANS",10000);
         WalletAnalyser k = new WalletAnalyser(w);
         LocalDateTime start = LocalDateTime.now().minusSeconds(10);
         w.addmoney(2000);
         w.deductmoney(300);
         w.deductmoney(850);
         w.deductmoney(1100);
        LocalDateTime end = LocalDateTime.now().plusSeconds(10);;
        assertEquals(2250, k.expenditure(start,end));
    }
    
}
